#!/usr/bin/env python3
"""LNA bias explorer in SPICE: coordinate descent over the five bias
voltages of low_noise_amp_fc_v3, maximizing AC gain at --fin (580 kHz).

Self-contained: embeds a voltage-driven copy of
xschem/low_noise_amp_fc_v3_loopgain_tb.sch (bias pins driven by vsource
parameters, as the DACs drive them on the chip), runs ngspice per point.

Defaults come from an OP solve of the original current-source testbench:
  vb1 = 0.7927  vb2 = 0.6466  tunep = 0.7094  iref = 1.1051  vref = 0.8
with vout DC = 0.80 (healthy). Points whose OP vout leaves
[--op-margin .. VDD -- op-margin] are rejected before the AC run --
out-of-headroom "gain" exists in simulation rather than on the chip.

Usage (from anywhere):
  ../.venv-meas/bin/python3 lna_bias_sim.py
  ../.venv-meas/bin/python3 lna_bias_sim.py --jobs 8 --grid 7 --passes 4

Output:
  lna_sim_log.csv    every evaluated point (biases, OP vout, gain dB)
  lna_sim_best.json  best set, keyed by CHIP DAC names (vref, vb1, vb2,
                     tunep, lna_iref) so lna_gain_tune.py --start can take it.

Chip name mapping (from the testbench instance
  x1 vss vb1 vb2 vout input vdd iref vref tunep):
  vref     -> vref (input-pair reference, TB node vr)
  vb1      -> vb1  (cascode bias XM25/XM26)
  vb2      -> vb2  (cascode bias XM17/XM24)
  tunep    -> tunep(active-cascode bias XM16/XM27)
  lna_iref -> iref (input-pair current-mirror gate XM5, TB node bufp)
"""

import argparse
import concurrent.futures as cf
import csv
import json
import math
import os
import re
import statistics
import subprocess
import sys
import tempfile
import threading
import time

PDK_LIB = "/storage/pdks/sky130A/libs.tech/ngspice/sky130.lib.spice"
VDD = 1.8

BIASES = {
    "lna_iref": {"node": "bufp",  "design": 1.105, "lo": 0.75,  "hi": 1.45},
    "vb1":      {"node": "vb1",   "design": 0.793, "lo": 0.55,  "hi": 1.05},
    "vb2":      {"node": "vb2",   "design": 0.647, "lo": 0.40,  "hi": 0.90},
    "tunep":    {"node": "tunep", "design": 0.709, "lo": 0.45,  "hi": 0.95},
    "vref":     {"node": "vr",    "design": 0.800, "lo": 0.65,  "hi": 0.95},
}

NETLIST_TMPL = """* auto-generated by lna_bias_sim.py -- voltage-driven copy of
* xschem/low_noise_amp_fc_v3_loopgain_tb.sch (bias pins driven like the chip DACs)
V2 VDD 0 1.8
XC1 vout 0 sky130_fd_pr__cap_mim_m3_1 W=22 L=22 MF=1
V8 vsen vr sin(0 {{vac}} {fin:g}) dc 0 ac 1
R1 vsen vin sky130_fd_pr__res_generic_l1 W=2 L=1
VB1  vb1   0 DC {vb1:g}
VB2  vb2   0 DC {vb2:g}
VTUN tunep 0 DC {tunep:g}
VIRE bufp  0 DC {iref:g}
VR   vr    0 DC {vref:g}
V1   net1  0 DC 0.8
XC6 net1 vr sky130_fd_pr__cap_mim_m3_1 W=8 L=8 MF=1
XM12 net2 net2 vr vr sky130_fd_pr__pfet_01v8_hvt L=3.0 W=1 nf=1 ad='int((nf+1)/2) * W/nf * 0.29' as='int((nf+2)/2) * (W/nf + 0.29)' pd='2*int((nf+1)/2) * (W/nf + 0.29)'
+ ps='2*int((nf+2)/2) * (W/nf + 0.29)' nrd='0.29 / W' nrs='0.29 / W' sa=0 sb=0 sd=0 mult=1
XM15 net2 net2 net1 net1 sky130_fd_pr__pfet_01v8_hvt L=3.0 W=1 nf=1 ad='int((nf+1)/2) * W/nf * 0.29' as='int((nf+2)/2) * (W/nf + 0.29)'
+ pd='2*int((nf+1)/2) * (W/nf + 0.29)' ps='2*int((nf+2)/2) * (W/nf + 0.29)' nrd='0.29 / W' nrs='0.29 / W' sa=0 sb=0 sd=0 mult=1
x1 0 vb1 vb2 vout vin VDD bufp vr tunep low_noise_amp_fc_v3
.lib {pdk} tt
.param vac = 5u
.options TEMP = 35.0
{subckt}
.control
  op
  print v(vout)
  ac dec 20 1e3 3e9
  meas ac G580 find vdb(vout) at={fin:g}
.endc
.end
"""

SUBCKT_FILE = "/storage/tue/aVLSI-SkyWater130-2024/netlists/low_noise_amp_fc_v3.spice"

_RE_VOUT = re.compile(r"v\(vout\)\s*=\s*([-\d.eE+]+)")
_RE_G580 = re.compile(r"g580\s*=\s*([-\d.eE+]+)", re.IGNORECASE)


def run_point(biases, fin, workdir, op_margin):
    vals = {name: biases[name] for name in BIASES}
    text = NETLIST_TMPL.format(
        pdk=PDK_LIB, fin=fin,
        vb1=vals["vb1"], vb2=vals["vb2"], tunep=vals["tunep"],
        iref=vals["lna_iref"], vref=vals["vref"],
        subckt=SUBCKT,
    )
    path = os.path.join(workdir, f"p_{threading.get_ident()}_{time.time_ns()}.spice")
    with open(path, "w") as f:
        f.write(text)
    try:
        r = subprocess.run(["ngspice", "-b", path], capture_output=True,
                           text=True, timeout=120)
        out = r.stdout
    except Exception:
        return None, None
    finally:
        try:
            os.unlink(path)
        except OSError:
            pass
    m = _RE_VOUT.search(out)
    vout_op = float(m.group(1)) if m else None
    if vout_op is None:
        return None, None
    if not (op_margin < vout_op < VDD - op_margin):
        return vout_op, None
    m = _RE_G580.search(out)
    gain_db = float(m.group(1)) if m else None
    return vout_op, gain_db


def gain_lin(db):
    return 10.0 ** (db / 20.0)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--fin", type=float, default=580e3)
    ap.add_argument("--grid", type=int, default=7)
    ap.add_argument("--passes", type=int, default=4)
    ap.add_argument("--jobs", type=int, default=8)
    ap.add_argument("--op-margin", type=float, default=0.05)
    ap.add_argument("--start", default="", help="JSON with starting biases")
    ap.add_argument("--log", default="lna_sim_log.csv")
    ap.add_argument("--best", default="lna_sim_best.json")
    args = ap.parse_args()

    if not os.path.exists(PDK_LIB):
        sys.exit(f"PDK lib required: {PDK_LIB}")

    global SUBCKT
    with open(SUBCKT_FILE) as f:
        raw = f.read()
    m = re.search(r"(\.subckt low_noise_amp_fc_v3.*?\.ends[^\n]*)", raw, re.S)
    if not m:
        sys.exit("extraction of low_noise_amp_fc_v3 subckt returned nothing")
    SUBCKT = m.group(1)

    current = {name: cfg["design"] for name, cfg in BIASES.items()}
    if args.start:
        with open(args.start) as f:
            loaded = json.load(f)
        biases_in = loaded.get("biases", loaded)
        for name in current:
            if name in biases_in:
                current[name] = float(biases_in[name])

    log_exists = os.path.exists(args.log)
    logf = open(args.log, "a", newline="")
    log = csv.writer(logf)
    if not log_exists:
        log.writerow(["t", "pass", "swept", "volts"] + list(BIASES) +
                     ["vout_op", "gain_db", "gain"])

    def measure(p):
        with tempfile.TemporaryDirectory(prefix="lnasim_") as wd:
            return run_point(p, args.fin, wd, args.op_margin)

    def eval_set(points):
        with cf.ThreadPoolExecutor(max_workers=args.jobs) as ex:
            return list(ex.map(measure, points))

    t0 = time.time()
    print(f"start biases: { {k: round(v,3) for k,v in current.items()} }")
    vout, g = measure(dict(current))
    if g is None:
        sys.exit(f"baseline OP unconverged (vout={vout}); template or PDK problem")
    best_db = g
    print(f"baseline: vout_op={vout:.3f} V, gain @ {args.fin/1e3:.0f} kHz = "
          f"{g:.2f} dB ({gain_lin(g):.0f} x)")
    log.writerow([f"{time.time():.3f}", 0, "start", ""] +
                 [f"{current[n]:.4f}" for n in BIASES] +
                 [f"{vout:.4f}", f"{g:.3f}", f"{gain_lin(g):.2f}"])
    logf.flush()

    best_biases = dict(current)
    r_lo, r_hi = 0.15, 0.85
    for cur_pass in range(1, args.passes + 1):
        span_frac = 0.5 * (0.45 ** (cur_pass - 1))
        for name, cfg in BIASES.items():
            span = (cfg["hi"] - cfg["lo"]) * span_frac
            lo = max(cfg["lo"], current[name] - span)
            hi = min(cfg["hi"], current[name] + span)
            pts = sorted({round(lo + (hi - lo) * (r_lo + (r_hi - r_lo) * i / (args.grid - 1)), 4)
                          for i in range(args.grid)} | {round(current[name], 4)})
            sets = []
            for v in pts:
                p = dict(current)
                p[name] = v
                sets.append(p)
            results = eval_set(sets)
            local_best_v, local_best_db = current[name], best_db
            for v, p, (vout_op, gdb) in zip(pts, sets, results):
                log.writerow([f"{time.time():.3f}", cur_pass, name, f"{v:.4f}"] +
                             [f"{p[n]:.4f}" for n in BIASES] +
                             [f"{vout_op:.4f}" if vout_op is not None else "",
                              f"{gdb:.3f}" if gdb is not None else "",
                              f"{gain_lin(gdb):.2f}" if gdb is not None else ""])
            logf.flush()
            for v, (vout_op, gdb) in zip(pts, results):
                if gdb is None:
                    continue
                if gdb > local_best_db:
                    local_best_v, local_best_db = v, gdb
            current[name] = local_best_v
            if local_best_db > best_db:
                best_db = local_best_db
                best_biases = dict(current)
                with open(args.best, "w") as bf:
                    json.dump({"biases": best_biases, "gain_db": best_db,
                               "gain": gain_lin(best_db), "fin_hz": args.fin,
                               "t": time.time()}, bf, indent=2)
            print(f"  pass{cur_pass} {name:9s} -> {current[name]:.3f} V   "
                  f"best {best_db:.2f} dB ({gain_lin(best_db):.0f} x)")

    dt = time.time() - t0
    print(f"\nDONE in {dt:.0f} s. best gain {best_db:.2f} dB "
          f"({gain_lin(best_db):.0f} x) @ {args.fin/1e3:.0f} kHz")
    print(f"best biases: {json.dumps(best_biases, indent=2)}")
    print(f"saved to {args.best} -- feed it to lna_gain_tune.py --start {args.best}")
    logf.close()


if __name__ == "__main__":
    sys.exit(main())
