#!/usr/bin/env python3
"""Emit the array digital pipeline's test vectors for on-silicon cycle counting.

The array-vs-digital energy table had exactly two measured rows -- the AER drain
(105 + 480/event) and the digital kernel (85215 cycles, on-chip via UART_CMD_OLFBENCH).
Everything the array needs to FEED and READ its neurons was estimated: the 8->16 random
projection, the level-crossing encoder, the exponential kernel features and the linear
read-out. Those estimates put the array's digital overhead at 3.8x the whole digital
baseline, which is far too load-bearing a number to leave modelled -- an estimate standing
in for a count is what produced the retracted 580x once already.

So this emits real data for each stage, and firmware/neuron_handshake times them on the
chip with Timer0 (UART_CMD_ARRAYBENCH 0xEF), exactly as the OP3 kernel is timed:

  proj_w[16][8]      the fixed random projection each neuron sees (rng 100+k), Q16
  olf_chunk[400]     one real 50 ms heater-cycle feature, Q16 (same vector as OP3 uses,
                     so the two kernels are counted on identical input)
  spk[16][150]       real spike counts per neuron per ms, from an archived acquisition
  clf_w[5][128]      a real logistic read-out fitted on the array's kernel features, Q16

Q16 throughout so the array pipeline is counted at the same precision as the Q16 digital
kernel it is compared against.

    PYTHONPATH=. ./.venv-meas/bin/python3 olfaction_export_arraypipe.py
"""
import argparse, glob, json
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from olfaction_iso_compare import kernel

Q = 16
SCALE = 1 << Q


def q(x):
    return int(np.clip(np.round(np.asarray(x) * SCALE), -2**31, 2**31 - 1))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spikes", default="")
    ap.add_argument("--out", default="firmware/olfaction_kernel/arraypipe.h")
    args = ap.parse_args()

    src = args.spikes or sorted(glob.glob("data/olfaction/olf_validate/centre_r*.npz"))[0]
    d = np.load(src, allow_pickle=True)
    sp, Y, it, T = d["spikes"], d["labels"], d["trial"], float(d["T"])
    nsteps = int(round(T * 1000))                       # 150 ms at 1 ms resolution
    n = sp.shape[0]

    # per-neuron spike counts on a 1 ms grid, from the real recording
    grid = np.zeros((n, nsteps), dtype=np.uint8)
    for u in range(n):
        for t in np.asarray(sp[u, 0], dtype=float):
            k = int(t * 1000.0)
            if 0 <= k < nsteps:
                grid[u, k] = min(255, grid[u, k] + 1)

    # the real read-out: kernel features -> logistic, fitted on this acquisition
    K = np.nan_to_num(kernel(sp, T))
    mdl = make_pipeline(StandardScaler(),
                        LogisticRegression(C=0.1, max_iter=5000,
                                           class_weight="balanced")).fit(K, Y)
    lr = mdl.named_steps["logisticregression"]
    sc = mdl.named_steps["standardscaler"]
    # fold the scaler into the weights so the firmware does one MAC per feature
    W = lr.coef_ / np.where(sc.scale_ == 0, 1, sc.scale_)
    B = lr.intercept_ - (lr.coef_ * sc.mean_ / np.where(sc.scale_ == 0, 1, sc.scale_)).sum(1)
    nfeat = W.shape[1]; ncls = W.shape[0]

    proj = np.stack([np.random.default_rng(100 + k).normal(0, 1, 8) for k in range(16)])

    with open(args.out, "w") as h:
        h.write("/* GENERATED by olfaction_export_arraypipe.py -- real data, Q16.\n"
                f"   spikes: {src}\n"
                "   Stages timed on silicon by UART_CMD_ARRAYBENCH (0xEF). */\n")
        h.write(f"#define AP_Q {Q}\n#define AP_UNITS 16\n#define AP_CHAN 8\n"
                f"#define AP_STEPS 50\n#define AP_TICKS {nsteps}\n"
                f"#define AP_NFEAT {nfeat}\n#define AP_NCLASS {ncls}\n"
                f"#define AP_NTAU 2\n#define AP_NSAMP {nfeat // (16 * 2)}\n\n")
        h.write("static const int ap_proj[AP_UNITS][AP_CHAN] = {\n")
        for u in range(16):
            h.write("  {" + ",".join(str(q(v)) for v in proj[u]) + "},\n")
        h.write("};\n\n")
        h.write("static const unsigned char ap_spk[AP_UNITS][AP_TICKS] = {\n")
        for u in range(16):
            h.write("  {" + ",".join(str(int(v)) for v in grid[u]) + "},\n")
        h.write("};\n\n")
        h.write("static const int ap_w[AP_NCLASS][AP_NFEAT] = {\n")
        for c in range(ncls):
            h.write("  {" + ",".join(str(q(v)) for v in W[c]) + "},\n")
        h.write("};\n\n")
        h.write("static const int ap_b[AP_NCLASS] = {"
                + ",".join(str(q(v)) for v in B) + "};\n\n")
        # exp(-1/tau) per tau, Q16, as the recursive decay factor
        taus = (0.010, 0.050)
        h.write("static const int ap_decay[AP_NTAU] = {"
                + ",".join(str(q(np.exp(-0.001 / t))) for t in taus) + "};\n\n")

        # ---- optimised-pipeline tables -------------------------------------------
        # (1) weights as Q8 COMPILE-TIME constants. At Q16 the product x*W overflows
        #     int32 (x is Q16, up to 18 bits); at Q8 it is 28 bits and fits, and a
        #     literal constant lets gcc strength-reduce the multiply into shifts/adds
        #     instead of calling the 16-iteration software routine.
        h.write("#define AP_QW 8\n")
        h.write("static const int ap_projq8[AP_UNITS][AP_CHAN] = {\n")
        for u in range(16):
            h.write("  {" + ",".join(str(int(round(v * 256))) for v in proj[u]) + "},\n")
        h.write("};\n")
        # LITERAL constants, unrolled over units. A runtime lookup ap_projq8[u][c]
        # forces gcc to emit a real multiply (__mulsi3, 16-iteration software routine);
        # only a compile-time literal lets it strength-reduce into shifts and adds. That
        # distinction is the whole optimisation, and getting it wrong once cost a build.
        h.write("__attribute__((always_inline)) static inline int "
                "ap_proj_dot(const int *x, int u)\n{\n  switch (u) {\n")
        for u in range(16):
            terms = "+".join(f"(((x)[{c}]*({int(round(proj[u][c]*256))}))>>8)"
                             for c in range(8))
            h.write(f"  case {u}: return {terms};\n")
        h.write("  default: return 0;\n  }\n}\n\n")
        # (2) decay^dt table. The recursive form multiplies EVERY tick (4800 times) but
        #     only the ticks with spikes matter, so each spike's contribution to a sample
        #     point is a table lookup and the stage becomes MULTIPLY-FREE.
        h.write(f"static const int ap_decaypow[AP_NTAU][AP_TICKS] = {{\n")
        for t in taus:
            h.write("  {" + ",".join(str(q(np.exp(-d * 0.001 / t)))
                                     for d in range(nsteps)) + "},\n")
        h.write("};\n\n")
        # (3) per-unit spike tick lists, so the kernel iterates over EVENTS not ticks
        counts = [int((grid[u] > 0).sum()) for u in range(16)]
        mx = max(1, max(counts))
        h.write(f"#define AP_MAXSPK {mx}\n")
        h.write("static const unsigned char ap_nspk[AP_UNITS] = {"
                + ",".join(str(c) for c in counts) + "};\n")
        h.write("static const unsigned char ap_spkt[AP_UNITS][AP_MAXSPK] = {\n")
        for u in range(16):
            ts = list(np.flatnonzero(grid[u] > 0))
            h.write("  {" + ",".join(str(int(t)) for t in ts + [0] * (mx - len(ts)))
                    + "},\n")
        h.write("};\n")
    print(f"wrote {args.out}: {nfeat} features, {ncls} classes, {nsteps} ticks")
    print(f"  spikes from {src}: {int(grid.sum())} events over {n} units")
    json.dump({"n_features": int(nfeat), "n_class": int(ncls), "ticks": int(nsteps),
               "events_in_vector": int(grid.sum()), "source": src},
              open("data/olfaction_arraypipe_vec.json", "w"), indent=2)


if __name__ == "__main__":
    raise SystemExit(main())
