#!/usr/bin/env python3
"""Export the olfaction OP3 tree model to C at a chosen fixed-point width.

The width is a DESIGN CHOICE for the digital baseline, with its own accuracy/cost
trade-off, so both operating points are exported and measured rather than one being
picked:

  Q8.8   cheaper -- int16 fields, smaller table -- but the resolution (3.9e-3) exceeds
         the smallest boosting leaf value (1.7e-3), so the smallest corrections round
         to ZERO and voted accuracy falls to 0.933.
  Q16    matches sklearn; costs a larger table and 32-bit loads.

The array must be compared at MATCHED ACCURACY, so which digital number it is priced
against depends on which accuracy it reaches.

    ./.venv-meas/bin/python3 olfaction_export_model.py --q 16
"""
import argparse, json
import numpy as np
from olfaction_identity import chunks
from sklearn.ensemble import HistGradientBoostingClassifier as HGB


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--q", type=int, default=16)
    ap.add_argument("--npz", default="data_olfaction/olfaction_pulses.npz")
    ap.add_argument("--outdir", default="firmware/olfaction_kernel")
    args = ap.parse_args()
    Q = args.q; S = float(1 << Q)
    wide = Q > 8                      # thresholds/values need int32 above Q8

    d = np.load(args.npz, allow_pickle=True)
    X, Th, y, meta = d["X"], d["T"], d["y"], d["meta"]
    cls = [str(c) for c in d["classes"]]
    t = np.arange(X.shape[1]) / 1000.0 + float(d["t0"]) / 1000.0
    dur = np.array([m[0] for m in meta])
    lab = np.array([{"b1": "Blank", "b2": "Blank"}.get(cls[k], cls[k]) for k in y])
    names = sorted(set(lab)); Y = np.array([names.index(v) for v in lab]); NC = len(names)

    tr = dur == "1.0s"; Ftr, itr = chunks(X[tr], Th[tr], t, 1.0, 0.05, tail=0.2)
    g = HGB(max_iter=10, max_leaf_nodes=8, random_state=0).fit(Ftr, Y[tr][itr])

    nodes, roots = [], []
    for s in g._predictors:
        for tr_ in s:
            roots.append(len(nodes)); n = tr_.nodes; off = len(nodes)
            for k in range(len(n)):
                isl = bool(n[k]["is_leaf"])
                nodes.append((int(n[k]["feature_idx"]) if not isl else 0,
                              int(round(float(n[k]["num_threshold"]) * S)) if not isl else 0,
                              int(n[k]["left"]) + off if not isl else 0,
                              int(n[k]["right"]) + off if not isl else 0,
                              int(round(float(n[k]["value"]) * S)) if isl else 0,
                              1 if isl else 0))

    def predict(x):
        xi = (x * S).astype(np.int64); sc = [0] * NC; c = 0
        for r in roots:
            i = r
            while not nodes[i][5]:
                f, thr, l, rt, _, _ = nodes[i]
                i = l if xi[f] <= thr else rt
            sc[c] += nodes[i][4]; c = (c + 1) % NC
        return int(np.argmax(sc))

    def visits(x):
        xi = (x * S).astype(np.int64); v = 0
        for r in roots:
            i = r
            while not nodes[i][5]:
                v += 1; f, thr, l, rt, _, _ = nodes[i]
                i = l if xi[f] <= thr else rt
        return v

    te = dur == "0.1s"; Fte, ite = chunks(X[te], Th[te], t, 0.1, 0.05, tail=0.2)
    yte = Y[te][ite]
    sk = g.predict(Fte); kp = np.array([predict(x) for x in Fte])
    vote = lambda p: float(np.mean([np.bincount(p[ite == j], minlength=NC).argmax()
                                    == yte[ite == j][0] for j in np.unique(ite)]))
    nv = float(np.mean([visits(x) for x in Fte]))
    agree = float((sk == kp).mean())
    print(f"Q{Q}: agreement with sklearn {agree:.4f}")
    print(f"  sklearn per-chunk {(sk==yte).mean():.3f}  voted {vote(sk):.3f}")
    print(f"  kernel  per-chunk {(kp==yte).mean():.3f}  voted {vote(kp):.3f}")
    print(f"  {nv:.1f} node visits/decision, table {len(nodes)*(16 if wide else 12)} bytes")

    ty = "int" if wide else "short"
    with open(f"{args.outdir}/model.h", "w") as h:
        h.write(f"/* GENERATED by olfaction_export_model.py --q {Q}. Edit the generator instead.\n"
                f" * {len(roots)} trees, {len(nodes)} nodes, {nv:.1f} node visits/decision.\n"
                f" * Agrees with sklearn on {agree*100:.1f}% of chunks; voted accuracy "
                f"{vote(kp):.3f} against sklearn's {vote(sk):.3f}.\n"
                f" * Q8.8 is NOT sufficient: its resolution (3.9e-3) exceeds the smallest\n"
                f" * boosting leaf value (1.7e-3), so small corrections round to zero.\n */\n")
        h.write(f"#define N_TREES {len(roots)}\n#define N_NODES {len(nodes)}\n"
                f"#define N_CLASS {NC}\n#define QSHIFT {Q}\n\n")
        h.write(f"typedef struct {{ short feat; short left; short right; short leaf; "
                f"{ty} thr; {ty} val; }} node_t;\n\n")
        h.write("static const unsigned short tree_root[N_TREES] = {"
                + ",".join(map(str, roots)) + "};\n\n")
        h.write("static const node_t node_tab[N_NODES] = {\n")
        for f, thr, l, r, v, lf in nodes:
            h.write(f"  {{{f},{l},{r},{lf},{thr},{v}}},\n")
        h.write("};\n")
    v0 = (Fte[0] * S).astype(np.int64)
    with open(f"{args.outdir}/testvec.h", "w") as tv:
        tv.write(f"/* GENERATED --q {Q}: one real 50 ms heater-cycle feature. */\n")
        tv.write(f"static const int olf_feat[{len(v0)}] = {{" + ",".join(map(str, v0)) + "};\n")
    json.dump({"q": Q, "agreement": agree, "visits_mean": nv, "n_trees": len(roots),
               "n_nodes": len(nodes), "table_bytes": len(nodes) * (16 if wide else 12),
               "distinct_features": len({n[0] for n in nodes if not n[5]}),
               "sk_chunk": float((sk == yte).mean()), "k_chunk": float((kp == yte).mean()),
               "sk_vote": vote(sk), "k_vote": vote(kp)},
              open(f"data/olfaction_model_stats_q{Q}.json", "w"), indent=2)


if __name__ == "__main__":
    raise SystemExit(main())
