#!/usr/bin/python3
from builtins import FileNotFoundError, len, open, print
import sys
import os
import json
import subprocess
import shutil

# Function to check if the folder exist
def does_folder_exist(folder_path):
    if not os.path.exists(folder_path):
        print(f"Error: The folder '{folder_path}' does not exist.")
        sys.exit(1)

# Function to check if the file exist in folder
def does_file_exist(folder_path, filename):
    if filename not in os.listdir(folder_path):
        print(f"Error: The file '{filename}' does not exist in the '{folder_path}' folder.")
        sys.exit(1)

# Function to load configuration from JSON file
def load_config(configname):
    try:
        with open(configname, 'r') as f:
            config = json.load(f)
        return config
    except FileNotFoundError:
        print(f"Error: Configuration file '{configname}' not found.")
        sys.exit(1)
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON format in configuration file '{filename}'.")
        sys.exit(1)

# Function to move files
def move_files(source_dir, target_dir, files_to_move):
    # Check if the target directory exists
    if not os.path.exists(target_dir):
        print(f'Target directory {target_dir} does not exist. Operation cancelled.')
        return
    
    for file_name in files_to_move:
        source_file = os.path.join(source_dir, file_name)
        target_file = os.path.join(target_dir, file_name)
        
        # Check if the source file exists
        if os.path.exists(source_file):
            # Move file
            shutil.move(source_file, target_file)
            print(f'Moved: {source_file} -> {target_file}')
        else:
            print(f'File {source_file} does not exist.')
        

# Load configuration from config.json
config = load_config('config.json')

magicpath = config["magicpath"]
xschempath = config["xschempath"]
netlistpath = config["netlistpath"]
spicepath = config["spicepath"]
scriptpath = config["scriptpath"]
extpath = config["extpath"]
allowed_processes = config["allowed_processes"]

# Check if the correct number of arguments are provided
if len(sys.argv) != 3:
    print("Usage: ./automation.py <filename> <lvs/pex/rcx>")
    sys.exit(1)

# Capture the variables from the command line arguments
filename = sys.argv[1]
process = sys.argv[2]
magicname = filename  + ".mag"
xschemname = filename + ".sch"
spicename = filename + ".spice"

# Check if the process is lvs, pex or rcx
if process not in allowed_processes:
    print("Error: The process must be 'lvs', 'pex', or 'rcx'.")
    sys.exit(1)

# Check if the filename contains a dot (.)
if filename.count(".") != 0:
    print(f"Error: The filename '{filename}' should not contain a dot (.)")
    sys.exit(1)

# Check if the folder "mag" exists
does_folder_exist(magicpath)

# Check if the folder "xschem" exists
does_folder_exist(xschempath)

# Check if the folder "netlist" exists
does_folder_exist(netlistpath)

# Check if the magic file exists in the "mag" folder
does_file_exist(magicpath, magicname)

# Check if the xschem file exists in the "xschem" folder
does_file_exist(xschempath, xschemname)

# Check if the spice file exists in the "netlist" folder
does_file_exist(netlistpath, spicename)

#lvsprocess 
if process == "lvs":
    does_folder_exist(spicepath)
    does_folder_exist(extpath)
    magic_command = f"""magic -dnull -noconsole -rcfile $PDK_ROOT/sky1384/libs.tech/magic/sky130A.magicrc << EOF
    # TCL script for extraction process
    load {filename}.mag
    flatten {filename}_lvs
    load {filename}_lvs
    select top cell
    extract path extfiles
    extract all
    ext2sim labels on
    ext2sim -p extfiles
    ext2spice lvs
    ext2spice -p extfiles
    """
    
    # Run the command using subprocess
    try:
        subprocess.run(magic_command, shell=True, check=True, cwd=magicpath)
    except subprocess.CalledProcessError as e:
        print(f"Error while running Magic: {e}")
    else:
        print("Magic LVS process completed successfully.")
    
    # Define the Tcl script filename
    tcl_script = os.path.join(magicpath, "generatedscript.tcl")
    # Define Tcl script content
    tcl_content = f"""
    #Tcl script generated by Python script
    # Set path of the layout spice file
    set layout_path [file normalize {magicpath}/{filename}_lvs.spice]
    # Set name of the layout cell
    set layout_name {filename}_lvs
    # Set path of the schematic spice file
    set schematic_path [file normalize {netlistpath}/{filename}.spice]
    # Set name of the schematic cell
    set schematic_name {filename}

    # Run script for netgen LVS
    # NOTE:  Assumes PDK_ROOT is set in the environment: $::env(PDK_ROOT).
    # NOTE:  Assumes PDK is set in the environment: $::env(PDK).
    # Script reads IP for the HD library from the PDK, then compares netlists.
    # Assumes that netgen is called with cwd = the directory above this one.
    set pdklib $::env(PDK_ROOT)/$::env(PDK)
    set techlibs ${{pdklib}}/libs.tech
    set reflibs ${{pdklib}}/libs.ref

    set setupfile ${{techlibs}}/netgen/sky130A_setup.tcl
    set hdlib ${{reflibs}}/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice

    set circuit1 [readnet spice {magicpath}/{filename}_lvs.spice]
    set circuit2 [readnet spice $hdlib]
    readnet spice {netlistpath}/{filename}.spice $circuit2

    lvs "$circuit1 {filename}_lvs" "$circuit2 {filename}" $setupfile
    """
    try:
        # Write Tcl script to file
        with open(tcl_script, "w") as f:
            f.write(tcl_content)

        # Run the Tcl script using netgen
        print("Running Tcl script...")
        netgen_command = f"netgen -batch source generatedscript.tcl"
        subprocess.run(netgen_command, check=True, cwd=magicpath, shell=True)

    except subprocess.CalledProcessError as e:
        print(f"Error running netgen: {e}")
    finally:
        # Delete the Tcl script
        print("Deleting Tcl script...")
        if os.path.exists(tcl_script):
            os.remove(tcl_script)

        print("Tcl script generated, executed, and deleted successfully.")

    files_to_move = [f'{filename}_lvs.spice', f'{filename}_lvs.sim', f'{filename}_lvs.nodes']
    move_files(magicpath, spicepath, files_to_move)

    files_to_move = ["comp.out"]
    move_files(magicpath, scriptpath, files_to_move)
    sys.exit(1)

#pexprocess 
if process == "pex":
    does_folder_exist(spicepath)
    does_folder_exist(extpath)
    magic_command = f"""magic -dnull -noconsole -rcfile .magicrc << EOF
    # TCL script for extraction process
    load {filename}.mag
    flatten {filename}_pex
    load {filename}_pex
    select top cell
    extract path extfiles
    extract all
    ext2sim labels on
    ext2sim -p extfiles
    ext2spice lvs
    ext2spice cthresh 0
    ext2spice -p extfiles
    """
    
    # Run the command using subprocess
    try:
        subprocess.run(magic_command, shell=True, check=True, cwd=magicpath)
    except subprocess.CalledProcessError as e:
        print(f"Error while running Magic: {e}")
    else:
        print("Magic PEX process completed successfully.")
    
    files_to_move = [f'{filename}_pex.spice', f'{filename}_pex.sim', f'{filename}_pex.nodes']
    move_files(magicpath, spicepath, files_to_move)
    sys.exit(1)
   
#rcxprocess 
if process == "rcx":
    does_folder_exist(spicepath)
    does_folder_exist(extpath)
    magic_command = f"""magic -dnull -noconsole -rcfile $PDK_ROOT/sky1384/libs.tech/magic/sky130A.magicrc << EOF
    # TCL script for extraction process
    load {filename}.mag
    flatten {filename}_rcx
    load {filename}_rcx
    select top cell
    extract path extfiles
    extract all
    ext2sim labels on
    ext2sim -p extfiles
    extresist tolerance 10
    extresist
    ext2spice lvs
    ext2spice cthresh 0
    ext2spice extresist on
    ext2spice -p extfiles
    """
    
    # Run the command using subprocess
    try:
        subprocess.run(magic_command, shell=True, check=True, cwd=magicpath)
    except subprocess.CalledProcessError as e:
        print(f"Error while running Magic: {e}")
    else:
        print("Magic RCX process completed successfully.")
    
    files_to_move = [f'{filename}_rcx.spice', f'{filename}_rcx.sim', f'{filename}_rcx.nodes']
    move_files(magicpath, spicepath, files_to_move)
    sys.exit(1)