#!/bin/bash

# Check if correct number of arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <layout_path> <layout_name> <schematic_path> <schematic_name>"
    exit 1
fi

# Assign command line arguments to parameters
layout_path="$1"
layout_name="$2"
schematic_path="$3"
schematic_name="$4"

# Check if <layout_name> contains '/'
if [[ "$layout_name" == *"/"* ]]; then
    echo "Error: layout_name cannot contain '/' character."
    exit 1
fi

# Check if <schematic_name> contains '/'
if [[ "$schematic_name" == *"/"* ]]; then
    echo "Error: schematic_name cannot contain '/' character."
    exit 1
fi

# Define the Tcl script filename
tcl_script="generated_script.tcl"

# Write Tcl script with parameter settings
cat <<EOF > "$tcl_script"
# Tcl script generated by shell script

# Set path of the layout spice file
set layout_path [file normalize $layout_path]
# Set name of the layout cell
set layout_name $layout_name
# Set path of the schematic spice file
set schematic_path [file normalize $schematic_path]
# Set name of the schematic cell
set schematic_name $schematic_name

# Run script for netgen LVS
#
# NOTE:  Assumes PDK_ROOT is set in the environment: $::env(PDK_ROOT).
# NOTE:  Assumes PDK is set in the environment: $::env(PDK).
# Script reads IP for the HD library from the PDK, then compares netlists.
# Assumes that netgen is called with cwd = the directory above this one.
set pdklib $::env(PDK_ROOT)/$::env(PDK)
set techlibs \${pdklib}/libs.tech
set reflibs \${pdklib}/libs.ref

set setupfile \${techlibs}/netgen/sky130A_setup.tcl
set hdlib \${reflibs}/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice

set circuit1 [readnet spice $layout_path]
set circuit2 [readnet spice \$hdlib]
readnet spice $schematic_path \$circuit2

lvs "\$circuit1 $layout_name" "\$circuit2 $schematic_name" \$setupfile

EOF

# Run the Tcl script
echo "Running Tcl script..."
netgen -batch source $tcl_script

# Delete the Tcl script
echo "Deleting Tcl script..."
rm "$tcl_script"

echo "Tcl script generated, executed, and deleted successfully."
